apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default

resources:
- ../deploy

patchesStrategicMerge:
- sandbox-config.yaml

# NOTE: This is used for testing only
# It is recommended to use the latest version of the operator
images:
- name: plexsystems/sandbox-operator
  newName: sandbox-operator
  newTag: dev
