apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default

resources:
- ../deploy

patchesStrategicMerge:
- sandbox-config.yaml

images:
- name: plexsystems/sandbox-operator
  newName: sandbox-operator
  newTag: dev
