apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- cluster-role-binding.yaml
- cluster-role.yaml
- sandbox-crd.yaml
- service-account.yaml
- user-default-role.yaml
